export const REPORT_INCOME_REQUEST='REPORT_INCOME_REQUEST';
export const REPORT_INCOME_SUCCESS='REPORT_INCOME_SUCCESS';
export const REPORT_INCOME_FAIL='REPORT_INCOME_FAIL';

export const REPORT_NUM_USER_REQUEST='REPORT_NUM_USER_REQUEST';
export const REPORT_NUM_USER_SUCCESS='REPORT_NUM_USER_SUCCESS';
export const REPORT_NUM_USER_FAIL='REPORT_NUM_USER_FAIL';

export const REPORT_NUM_PRODUCT_REQUEST='REPORT_NUM_PRODUCT_REQUEST';
export const REPORT_NUM_PRODUCT_SUCCESS='REPORT_NUM_PRODUCT_SUCCESS';
export const REPORT_NUM_PRODUCT_FAIL='REPORT_NUM_PRODUCT_FAIL';

export const REPORT_NUM_BLOG_REQUEST='REPORT_NUM_BLOG_REQUEST';
export const REPORT_NUM_BLOG_SUCCESS='REPORT_NUM_BLOG_SUCCESS';
export const REPORT_NUM_BLOG_FAIL='REPORT_NUM_BLOG_FAIL';

export const REPORT_NUM_ORDER_REQUEST='REPORT_NUM_ORDER_REQUEST';
export const REPORT_NUM_ORDER_SUCCESS='REPORT_NUM_ORDER_SUCCESS';
export const REPORT_NUM_ORDER_FAIL='REPORT_NUM_ORDER_FAIL';